### ISSUE TITLE
Problem with benepar.download("benepar_en")

### ISSUE THREAD

**Issue by toto222** [nikitakit/self-attentive-parser#10] opened 2018-10-22 10:10 UTC
Hi, 

I want to use benepar, so I try to download benepar_en with this code:
```python
import benepar
benepar.download("benepar_en")
```

I have this result:
```
[nltk_data] Downloading package benepar_en to
[nltk_data]     /Users/azerafelie/nltk_data...
```
And no download (I waited 30min), when I go to this folder, I have the file benepar_en created, but its size is 0KB...

How can I solve that please ?

I try this on another computer, same things...

Best,

**Comment by nikitakit** [comment] 2018-10-22 20:05
The model releases are hosted on GitHub, and GitHub had an outage starting last night (see https://status.github.com/messages). I'm guessing that the download has already become available, or will become available once the status page goes 100% green again. Hopefully this issue is a one-time event.

**Comment by nikitakit** [comment] 2018-10-27 05:47
I'm closing this issue since I'm pretty sure it was caused by the GitHub outage. Please let me know if the situation persists and I should re-open and look into this further.

**Closed by nikitakit** 2018-10-27 05:47 UTC
